# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "ubuntu1310-mesos"

  config.vm.provision :shell, :path => "bootstrap-mesos-master.sh"

  config.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

end
