# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "ubuntu1310-docker"

  config.vm.provision :shell, :path => "bootstrap-mesos.sh"

  config.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)"
  
end
